name: star_printer_ios
description: iOS implementation of the star_printer plugin.
version: 1.0.0
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: star_printer
    platforms:
      ios:
        pluginClass: StarPrinterPlugin

dependencies:
  flutter:
    sdk: flutter
